version: '3'
services:
  app: &backend
    build: .
    entrypoint: sh ./docker-entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app:cached

  web:
    <<: *backend
    command: sleep infinity
    restart: always
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
